name: 'book-store'
services:
  catalog_db:
    image: mysql:latest
#    container_name: catalog_db
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: catalog_db
      MYSQL_USER: root
      MYSQL_PASSWORD: pass123
    ports:
      - "15432:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -ppass123" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m